// <auto-generated />
namespace Cashflow.Bot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class subscriptions2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subscriptions2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103260820211_subscriptions2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
